name: simple_selector
description: A simple and customizable selector widget with animated transition.
version: 1.0.8
homepage: https://github.com/sameteyisan/simple_selector.git

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
